# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: 버전 Tag push 시 Config Update

on:
  # Runs on pushes targeting the default branch
  push:
    tags: "*"
    
  workflow_dispatch:
  
  

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.108.0
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: setup-yq
        uses: mikefarah/yq@v4.33.2
        
      - name: Release File Found Test
        run: wget --spider "https://github.com/yunwoopc-dev/Release/releases/download/${{ steps.tagName.outputs.tag }}/Hub-${{ steps.tagName.outputs.tag }}.exe"
        
      - name: Change Download
        run: |
          yq -i '.params.hero.button.name = "Install v'${{ steps.tagName.outputs.tag }}'"' config.yaml
          yq -i '.params.hero.button.url = "https://yw-dev.synology.me:18081/repository/raw_test/hub_windows_app/Hub.'${{ steps.tagName.outputs.tag }}'.exe"' config.yaml
          
      - name: Git Checkout
        run: |
          git fetch
          git checkout main
          git pull
          
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: main
          commit-message: "${{ steps.tagName.outputs.tag }}"
          email: "github-actions[bot]@users.noreply.github.com"
          name: "github-actions[bot]"
          files: config.yaml
